"""initial schema

Revision ID: ef7c7c6dd2f4
Revises: 
Create Date: 2026-05-28 16:34:14.709158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7c7c6dd2f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_preferences',
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_threshold', sa.String(length=10), nullable=True),
    sa.Column('notification_pref', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('manager_id', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('intervention_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_computed_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=False),
    sa.Column('trend_delta', sa.Integer(), nullable=True),
    sa.Column('trend_direction', sa.String(length=10), nullable=True),
    sa.Column('signal_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_computed_scores_member_id'), 'pre_computed_scores', ['member_id'], unique=False)
    op.create_table('role_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('expected_meeting_hrs', sa.Integer(), nullable=False),
    sa.Column('focus_time_min_hrs', sa.Integer(), nullable=False),
    sa.Column('overload_threshold', sa.Integer(), nullable=False),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_baselines')
    op.drop_index(op.f('ix_pre_computed_scores_member_id'), table_name='pre_computed_scores')
    op.drop_table('pre_computed_scores')
    op.drop_table('intervention_log')
    op.drop_table('employees')
    op.drop_table('employee_preferences')
    # ### end Alembic commands ###
